#include <stdio.h>
#include <string.h>
#include <stdio.h>
#include <pthread.h>
#include <inttypes.h>
/* This is generated by a template program */


#define CQUEUE_SIZE 10

typedef struct cqueue_s {
    int head;
    int tail;
    int count;
    pthread_mutex_t queue_lock;
    int data[CQUEUE_SIZE];
}cqueue_t;

void print_queue(cqueue_t q_data){
    int i = 0;
    for(i = 0; i < CQUEUE_SIZE; i++){
        printf("--%d--", q_data.data[i]);
    }
    printf("\n");
}
void reset_queue(cqueue_t *q_data){
   memset(q_data, 0, sizeof(cqueue_t));
   q_data->head = 0;
   q_data->tail = 0;
}

void enqueue(cqueue_t* queue, int data){

    if(queue->count == CQUEUE_SIZE){
        printf("QUEUE is full. Please dequeue\n");
    }else{

        queue->data[queue->tail] = data;
        print_queue(*queue);

        queue->tail = (++queue->tail)%CQUEUE_SIZE;//For going to starting.
        queue->count++;
    }
}

int dequeue(cqueue_t* queue){

    int temp;
    temp = queue->data[queue->head];

    queue->data[queue->head] = 0;
    queue->head++;
    queue->count --;
    return temp;
}

int main(){

    cqueue_t q_main;
    int i =0

    uint8_t input[20]= {11, 12, 13, 14, 15, 16, 17, 18 , 19, 20 , 21, 22, 23, 24, 25, 26, 27, 28};
    reset_queue(&q_main);
    for( i = 0; i < 11; i ++){
        enqueue(&q_main, input[i]);
    }
    printf("Got data from queue: %d\n", dequeue(&q_main));
    printf("Got data from queue: %d\n", dequeue(&q_main));
    printf("Got data from queue: %d\n", dequeue(&q_main));
        enqueue(&q_main, input[13]);
        enqueue(&q_main, input[14]);
        enqueue(&q_main, input[15]);
        enqueue(&q_main, input[16]);
    return 0;
}

